### ISSUE TITLE
File path '/*' shows as comment

### ISSUE THREAD

**Issue by gbateman** [google/language-jsonnet#7] opened 2019-01-16 00:24 UTC
I have a file with '/path/to/file/*' in a string, and the entire rest of the file is being highlighted as if it were a multi-line comment. However, since this is inside of a string, it should not create a comment, just like in atom's default js syntax highlighting.

<img width="149" alt="screen shot 2019-01-15 at 4 24 06 pm" src="https://user-images.githubusercontent.com/14298838/51218601-15448b80-18e2-11e9-8ad1-4df4bf6b7e2f.png">

**Comment by sparkprime** [comment] 2019-03-11 15:25
I can't reproduce this anymore, it might have been fixed by adding the ' string.

**Closed as completed by sparkprime** 2019-03-11 15:25 UTC

**Comment by pichouk** [comment] 2019-06-25 14:24
I have a similar issue but with a multi-line string, here a sample to reproduce :
```
{
  key: value,
  multiline: |||
    this is a multiline string
    and a path like this one (/var/log/*.log)
    triggers a comment
  |||,
}
```

The `/*` made the entire document to be shown as a comment.

**Comment by sparkprime** [comment] 2019-06-25 14:49
I don't think atom supports that because of the meaningful whitespace.  You need to be able to write a custom lexer rather than just match tokens with regex.  Codemirror can do it, for example. https://github.com/google/codemirror-mode-jsonnet
